# Generated by Django 3.2 on 2021-04-22 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_auto_20210422_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isbn',
            fields=[
                ('isbn_num', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.isbn'),
        ),
    ]
