# Generated by Django 3.2 on 2021-04-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210422_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='isbn',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
