# Generated by Django 3.2 on 2021-04-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_isbn_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isbn',
            name='author',
        ),
        migrations.RemoveField(
            model_name='isbn',
            name='name',
        ),
        migrations.AddField(
            model_name='isbn',
            name='book_author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='books.Category'),
        ),
    ]
